### ISSUE TITLE
triggermesh staging does not handle ContainerSource

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/aws-event-sources#137]
While trying to launch a SQS source as a ContainerSource it failed with:

```
$ kubectl logs aws-sqs-source6t9fn-deployment-cf99c7f7b-2mkw4 -n sebgoa
time="2020-05-14T19:12:18Z" level=fatal msg="http target option was empty string"
```

manifest is:

```
apiVersion: sources.knative.dev/v1alpha2
kind: ContainerSource
metadata:
  name: aws-sqs-source6t9fn
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Broker
      name: default
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K_LOGGING_CONFIG
          value: '{"level":"info"}'
        - name: K_METRICS_CONFIG
          value: '{"domain":"triggermesh.io/sources","component":"awssqssource","configMap":{}}'
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws_access_key_id
              name: awscreds
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws_secret_access_key
              name: awscreds
        - name: AWS_REGION
          value: us-east-1
        - name: QUEUE
          value: triggermesh
        image: gcr.io/triggermesh/awssqs:latest
        name: source
        resources: {}
```
