### ISSUE TITLE
be able to pass annotations to the generated pods

### ISSUE THREAD

**Issue by davidkarlsen** [triggermesh/aws-event-sources#252]
See https://github.com/triggermesh/aws-event-sources/issues/251.
I want to be able to set annotations on the pods generated from the trigger mesh custom resources, in order to do istio side-car injection on openshift. This is only possible through annotating the pods when using openshift, not via namespace labelling.

**Comment by antoineco** [comment]
@davidkarlsen I've been thinking about this a little bit more and had an idea I wanted to share with you.

Just passing annotations wouldn't fit all scenarios, because we cannot know for sure whether the user wants to have those annotations set on:

* both the Deployment metadata and Pod template 
* just the Pod template
* just the Deployment
* which Pod(s), if the event source runs more than one Pod (we have that case in another repo)
* a mixture of that: what annotation is set where?

Besides, in the future someone may require the injection of extra environment variables (`http_proxy` is just one example), or want to customize container-level resources and limits, etc. and this doesn't fit in the abstraction offered by CRDs anymore.

Kubernetes used to have something called [PodPresets](https://kubernetes.io/docs/tasks/inject-data-application/podpreset/) for this kind of use case, but it was removed recently 😞. The current "recommended" way to inject extra configuration into arbitrary objects upon creation/update is to create an admission controller (https://docs.giantswarm.io/guides/creating-your-own-admission-controller/), but this is quite involved just for adding an annotation...

My proposal is that we implement a configuration object that can be used to bind annotations to any Kubernetes object: Deployments, Pods, custom objects... The spec could look like this (it is very much inspired by https://github.com/mattmoor/bindings):

```yaml
apiVersion: settings.triggermesh.io/v1
kind: AnnotationsBinding
metadata:
  name: istio-injection

spec:

  # 'subject' selects what object(s) the binding applies to, either by name or label selector
  subject:
    apiVersion: v1
    kind: Pod
    selector:
      matchLabels:
        # applies to all AWS event sources
        app.kubernetes.io/part-of: aws-event-sources
        # applies to all SQS event sources
        app.kubernetes.io/name: awssqssource
        # applies to a specific SQS event source
        app.kubernetes.io/instance: my-source

  # 'values' is a map of annotations to inject into the object(s) selected by 'subject'
  values:
    sidecar.istio.io/inject: 'true'
    other.istio.annotation: some value
```

If the Pod that runs the SQS source is created like this:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: awssqssource-my-source
  labels:
    app.kubernetes.io/part-of: aws-event-source
    app.kubernetes.io/name: awssqssource
    app.kubernetes.io/instance: my-source
spec:
  containers:
  - names: adapter
    env:
    - name: ARN
      value: arn:aws:sqs:us-east-2:123456789012:my-queue
    - name: K_SINK
      value: http://...
    # ...
```

then the binding will ensure the following annotations are always present:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: awssqssource-my-source
  labels:
    app.kubernetes.io/part-of: aws-event-source
    app.kubernetes.io/name: awssqssource
    app.kubernetes.io/instance: my-source
    
    # injected by the binding
    annotations:
      sidecar.istio.io/inject: 'true'
      other.istio.annotation: some value

spec:
  containers:
  - names: adapter
    env:
    - name: ARN
      value: arn:aws:sqs:us-east-2:123456789012:my-queue
    - name: K_SINK
      value: http://...
    # ...
```

Does that sound like something that could help with your use case, or is the overhead not worth the effort compared to deploying Pods manually?
