### ISSUE TITLE
MetricQuery supports neither GroupBy nor Filter

### ISSUE THREAD

**Issue by antoineco** [triggermesh/aws-event-sources#284]
The current spec contains a single `metricQuery` field which semantics is confusing because it doesn't translate to a full metric query, but rather to the specific `Metric` field of a metric query:

https://github.com/triggermesh/aws-event-sources/blob/56307ae71d80c3d2c9db2931d7e0f3e0aabfb2fa/pkg/adapter/awsperformanceinsightssource/adapter.go#L93

API doc:
https://docs.aws.amazon.com/performance-insights/latest/APIReference/API_GetResourceMetrics.html

If we ever want to let users express full metric queries, we will need to switch to a more structured spec, such as (expressed as OpenAPI schema):

```yaml
metricQuery:
  type: object
  properties:
    metric:
      type: string
    filter:
      type: string
    groupBy:
      type: object
      properties:
        group:
          type: string
        dimensions:
          type: array
          items:
            type: string
        limit:
          type: integer
      required:
      - group
  required:
  - metric
```

The Go structs used within the AWS SDK are documented here:
- [pi.MetricQuery](https://docs.aws.amazon.com/sdk-for-go/api/service/pi/#MetricQuery)
- [pi.DimensionGroup](https://docs.aws.amazon.com/sdk-for-go/api/service/pi/#DimensionGroup)

cc @JeffNeff FYI
