### ISSUE TITLE
CodeCommit: SerializationError upon event processing

### ISSUE THREAD

**Issue by antoineco** [triggermesh/aws-event-sources#58]
Upon pushing a commit to the observed repository, the source fails with a  SerializationError:

```
time="2020-04-07T19:54:35Z" level=info msg="Push Events Enabled!"
time="2020-04-07T19:54:36Z" level=info msg="Pull Request Events Enabled!"
time="2020-04-07T19:58:06Z" level=error msg="SerializationError: failed to unmarshal response error\n\tstatus code: 400
, request id: 8b8b7d42-6ad1-484d-82aa-229a602e9403\ncaused by: UnmarshalError: failed decoding error message\n\t0000000
0  3c 54 68 72 6f 74 74 6c  69 6e 67 45 78 63 65 70  |<ThrottlingExcep|\n00000010  74 69 6f 6e 3e 0a 20 20  3c 4d 65 73
 73 61 67 65  |tion>.  <Message|\n00000020  3e 52 61 74 65 20 65 78  63 65 65 64 65 64 3c 2f  |>Rate exceeded</|\n00000
030  4d 65 73 73 61 67 65 3e  0a 3c 2f 54 68 72 6f 74  |Message>.</Throt|\n00000040  74 6c 69 6e 67 45 78 63  65 70 74
69 6f 6e 3e 0a  |tlingException>.|\n\ncaused by: invalid character '<' looking for beginning of value"
time="2020-04-07T20:41:10Z" level=error msg="SerializationError: failed to unmarshal response error\n\tstatus code: 400
, request id: 7676f2b8-ab78-47a3-bd23-139983973551\ncaused by: UnmarshalError: failed decoding error message\n\t0000000
0  3c 54 68 72 6f 74 74 6c  69 6e 67 45 78 63 65 70  |<ThrottlingExcep|\n00000010  74 69 6f 6e 3e 0a 20 20  3c 4d 65 73
 73 61 67 65  |tion>.  <Message|\n00000020  3e 52 61 74 65 20 65 78  63 65 65 64 65 64 3c 2f  |>Rate exceeded</|\n00000
030  4d 65 73 73 61 67 65 3e  0a 3c 2f 54 68 72 6f 74  |Message>.</Throt|\n00000040  74 6c 69 6e 67 45 78 63  65 70 74
69 6f 6e 3e 0a  |tlingException>.|\n\ncaused by: invalid character '<' looking for beginning of value"
time="2020-04-07T20:42:44Z" level=info msg="send Commit Event"
```
Pod manifest
```yaml
spec:
  containers:
  - name: adapter
    image: gcr.io/triggermesh/awscodecommit
    args:
    - -sink=http://default-broker.dev.svc.cluster.local
    env:
    - name: REPO
      value: source-test
    - name: BRANCH
      value: master
    - name: AWS_REGION
      value: eu-central-1
    - name: EVENTS
      value: pull_request,push
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          key: aws_access_key_id
          name: awscreds
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: aws_secret_access_key
          name: awscreds
```
